workspace:
  base: /go
  path: src/github.com/isfang/drone-test

pipeline:
  test:
    image: golang:latest
    commands:
      - pwd
      - ls

  build:
    imgage:golang:latest
    commands:
      - curl http://www.sina.com.cn
      - curl http://www.baidu.com
      - curl http://www.iot.com
  build:
    image: golang:latest
    commands:
      - echo 111
      - go run mergeSort.go
